@startuml c4_contexto
!include ../../../commons/plantuml_config.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()
title Diagrama C4 - Nivel 1: Contexto

Person(user, "Usuario Lector", "Busca recomendaciones de libros")
System(bookmate, "Sistema BookMate", "Plataforma de recomendaciones inteligentes")

Rel(user, bookmate, "Usa", "HTTPS")

@enduml

