@startuml estados_libro
!include ../../commons/plantuml_config.puml

title Diagrama de Estados - Libro en Biblioteca Personal

[*] --> NoAgregado

NoAgregado --> PorLeer : agregar_libro()
PorLeer --> Leyendo : marcar_leyendo()
Leyendo --> Leido : marcar_leido()
PorLeer --> Leido : marcar_leido()
Leyendo --> PorLeer : pausar_lectura()
Leido --> Leyendo : releer()

PorLeer --> NoAgregado : eliminar_libro()
Leyendo --> NoAgregado : eliminar_libro()
Leido --> NoAgregado : eliminar_libro()

NoAgregado --> [*]

@enduml

