@startuml proceso_futuro
!include ../../../commons/plantuml_config.puml

title Proceso Futuro con BookMate (TO-BE)

|Usuario|
start
:Inicia sesión en BookMate;
:Agrega libros a biblioteca;

|Sistema BookMate|
:Analiza biblioteca;
:Genera recomendaciones;

|Usuario|
:Recibe top 5 libros personalizados;
stop

@enduml
